"""
context_monitor.py — AdaptiveOrchestrator Sprint 3
Measures RTT and CPU every 500ms, decides operational mode,
writes structured JSONL logs as thesis evidence.

Sprint 3 change: thresholds loaded from config/calibration.json
at startup. Falls back to hardcoded defaults if file not found.
Calibration file generated by edge/telemetry/calibrate.py.
"""

import asyncio
import json
import os
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path

import psutil

# ── Calibration loader ────────────────────────────────────────
SCRIPT_DIR       = Path(__file__).parent
CALIBRATION_PATH = SCRIPT_DIR.parent.parent / "config" / "calibration.json"

# Hardcoded Sprint 2 defaults — only used if calibration.json missing
_DEFAULT_LATENCY_THRESHOLD = 500.0   # ms
_DEFAULT_CPU_THRESHOLD     = 80.0    # %
_DEFAULT_HYSTERESIS        = 3

def load_thresholds() -> tuple[float, float, int, str]:
    """
    Load thresholds from calibration.json.
    Returns (latency_ms, cpu_pct, hysteresis, source_label).
    Falls back to hardcoded defaults if file not found.
    """
    if CALIBRATION_PATH.exists():
        try:
            cal = json.loads(CALIBRATION_PATH.read_text())
            t   = cal["thresholds"]
            lat = float(t["latency_ms"])
            cpu = float(t["cpu_pct"])
            hys = int(t.get("hysteresis", _DEFAULT_HYSTERESIS))
            ts  = cal.get("calibrated_at", "unknown")
            alg = cal.get("algorithm", "")
            label = f"calibration.json (calibrated {ts[:10]})"
            return lat, cpu, hys, label, alg
        except Exception as e:
            print(f"[WARN] Failed to parse calibration.json: {e}")
            print("[WARN] Falling back to hardcoded Sprint 2 defaults.")
    else:
        print(f"[WARN] calibration.json not found at: {CALIBRATION_PATH}")
        print("[WARN] Run calibrate.py first. Using hardcoded Sprint 2 defaults.")

    return (
        _DEFAULT_LATENCY_THRESHOLD,
        _DEFAULT_CPU_THRESHOLD,
        _DEFAULT_HYSTERESIS,
        "HARDCODED DEFAULTS (Sprint 2 fallback)",
        "no calibration"
    )

# ── Load thresholds at import time ────────────────────────────
LATENCY_THRESHOLD, CPU_THRESHOLD, HYSTERESIS_COUNT, CAL_SOURCE, CAL_ALG = load_thresholds()

# ── Configuration ─────────────────────────────────────────────
CLOUD_HOST        = "172.28.0.20"
SAMPLE_INTERVAL_S = 0.5
LOG_PATH          = "/logs/context_monitor.jsonl"

MODE_CLOUD      = "CLOUD_OPTIMISED"
MODE_EDGE       = "EDGE_ONLY"
MODE_AUTONOMOUS = "EDGE_AUTONOMOUS"

os.makedirs("/logs", exist_ok=True)

# ── Measurement ───────────────────────────────────────────────
def measure_rtt_ms(host: str) -> float:
    try:
        result = subprocess.run(
            ["ping", "-c", "1", "-W", "2", host],
            capture_output=True, text=True, timeout=3
        )
        for line in result.stdout.split("\n"):
            if "time=" in line:
                return float(line.split("time=")[1].split(" ")[0])
        return -1.0
    except Exception:
        return -1.0

def measure_cpu_pct() -> float:
    return psutil.cpu_percent(interval=None)

# ── Mode decision ─────────────────────────────────────────────
def decide_mode(rtt_ms: float, cpu_pct: float) -> str:
    if rtt_ms < 0:
        return MODE_AUTONOMOUS
    if rtt_ms > LATENCY_THRESHOLD or cpu_pct > CPU_THRESHOLD:
        return MODE_EDGE
    return MODE_CLOUD

# ── Output ────────────────────────────────────────────────────
def write_log(entry: dict):
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps(entry) + "\n")

def print_status(e: dict):
    rtt = f"{e['rtt_ms']:.1f}ms" if e['rtt_ms'] >= 0 else "UNREACHABLE"
    breach = ""
    if e['latency_breach']: breach += "  ⚠ LATENCY"
    if e['cpu_breach']:     breach += "  ⚠ CPU"
    print(f"[{e['ts'][11:19]}]  RTT={rtt:>12}  CPU={e['cpu_pct']:>5.1f}%  "
          f"mode={e['mode']:<20}{breach}")

# ── Main loop ─────────────────────────────────────────────────
async def run():
    print("=" * 66)
    print(" AdaptiveOrchestrator — Context Monitor  (Sprint 3)")
    print(f" Thresholds source : {CAL_SOURCE}")
    print(f" Algorithm         : {CAL_ALG}")
    print(f" latency_threshold : {LATENCY_THRESHOLD} ms")
    print(f" cpu_threshold     : {CPU_THRESHOLD} %")
    print(f" hysteresis        : {HYSTERESIS_COUNT} consecutive breaches")
    print(f" Log               : {LOG_PATH}")
    print("=" * 66)

    psutil.cpu_percent(interval=None)   # warm up
    await asyncio.sleep(0.5)

    current_mode  = MODE_CLOUD
    breach_count  = 0
    sample_number = 0

    while True:
        t0 = time.monotonic()

        rtt_ms  = measure_rtt_ms(CLOUD_HOST)
        cpu_pct = measure_cpu_pct()
        raw     = decide_mode(rtt_ms, cpu_pct)

        # hysteresis — prevent flapping on transient spikes
        if raw == MODE_AUTONOMOUS:
            # Outage: switch immediately, no hysteresis wait
            breach_count = HYSTERESIS_COUNT
        elif raw != MODE_CLOUD:
            breach_count += 1
        else:
            breach_count = 0

        if breach_count >= HYSTERESIS_COUNT or raw == MODE_CLOUD:
            if raw != current_mode:
                print(f"\n{'─'*66}")
                print(f"  *** MODE SWITCH: {current_mode} → {raw} ***")
                print(f"{'─'*66}\n")
            current_mode = raw

        entry = {
            "ts":              datetime.now(timezone.utc).isoformat(),
            "sample":          sample_number,
            "rtt_ms":          round(rtt_ms, 3),
            "cpu_pct":         round(cpu_pct, 1),
            "cloud_reachable": rtt_ms >= 0,
            "latency_breach":  rtt_ms > LATENCY_THRESHOLD,
            "cpu_breach":      cpu_pct > CPU_THRESHOLD,
            "mode":            current_mode,
            "breach_count":    breach_count,
            "thresholds": {
                "latency_ms": LATENCY_THRESHOLD,
                "cpu_pct":    CPU_THRESHOLD,
            },
        }
        write_log(entry)
        print_status(entry)

        sample_number += 1
        await asyncio.sleep(max(0, SAMPLE_INTERVAL_S - (time.monotonic() - t0)))

if __name__ == "__main__":
    asyncio.run(run())